AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template for creating DynamoDB resources

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: http-crud-items
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  DynamoDBTableName:
    Value: !Ref DynamoDBTable # Retourne le nom de la table
    Description: The name of the DynamoDB table

  DynamoDBTableArn:
    Value: !GetAtt DynamoDBTable.Arn # Retourne l'ARN de la table DynamoDB
    Description: The ARN of the DynamoDB table